### ISSUE TITLE
QR code detected but without pose

### ISSUE THREAD

**Issue by 9and3** [LocalJoost/QRCodeService#1]
First things first, thank you so much for sharing your amazing detection tool. You have maybe no idea how long I have been searching for implementation of QR code into Unity for Hololens2, this is amazing.
Although it detects the QR code (see debug log in image), there is no airplane appearing in the holographic render either in the editor space in Unity. It almost seems that the pose doesn't work in my case.

My env. : I just open the Unity project straight from your repo.

Here's a screenshot: https://i.gyazo.com/6750c319a46329cab26dcd9e42d89519.png
And here's the QR code I am trying to open: https://fiverr-res.cloudinary.com/images/q_auto,f_auto/gigs/144590579/original/61d0e370b940f1a5c0b7ec89c72ba8bab0dfb9b1/can-create-a-professional-and-amazing-qr-code.png

Thanks in advance and thank you again for this nice free tool!

**Comment by LocalJoost** [comment]
Hi my friend,
First, thanks for your compliments. It's always nice to notice I am not simply screaming into the void ;)

Having said that, I have some bad news for you. This code for positioning will only work _runtime, in a HoloLens 2_. If you will look at the [SpatialGraphCoordinateSystemSetter](https://github.com/LocalJoost/QRCodeService/blob/main/Assets/MRTKExtensions/QRCodes/SpatialGraphCoordinateSystemSetter.cs), lines 66-80, you will see that the crucial code for actually obtaining the coordinate systems and calculating the first pose is _between preprocessor statements_ (#if WINDOWS_UWP) that will only make them execute in a HoloLens. This is because the API called is only available to UWP apps, not the Unity editor. I am actually surprised the first step - detecting the QR code _itself_ - works in the editor.

So, apologies, this is not going to work running from the editor. You need to build the app and deploy to a device. Then and only then the positioning will work. I am sorry I apparently did not make that clear. 

I see you have more or less logged [the exact same problem on the original Microsoft sample](https://github.com/chgatla-microsoft/QRTracking/issues/27) ;). I hope this make clear what is going wrong at your side.

**Comment by 9and3** [comment]
Hello and thank you so much for your answer and explanation. I have indeed scattered the internet with the same question basically:) and now finally I know where is the problem.. great, much appreciated!
Do you think having a tracking system running directly from the editor (without deployment on the device) is technically impossible? I mean the QR code is continuously detected so as you said it's kind of a surprise now that I know what is wrong.

**Comment by LocalJoost** [comment]
You are welcome. I can't say with certainty that it is totally impossible to run a tracking system from the editor - after all, Vuforia manages to do this - but I think with would quite some fiddling. Also, it's use would be very limited, especially compared to the effort.
