### ISSUE TITLE
QRCode model positioning development error

### ISSUE THREAD

**Issue by HUIMANDY** [LocalJoost/QRCodeService#5]
Hello, we use QRCode services for model positioning development, but errors will occur when using the function  “”Unity-XR-Holographic Emulation / Hololens2-Holographic Remoting ”” . 
The QRcode can be scanned during the first play, but its marker appears at the origin position(0,0,0) ,it isn’t positioned correctly. 
After playing again, there will be an error called “ COMexception” 

We Use 
-	UNITY2019.4
-	MRTK2.4 and 2.5.1
-       Hololens2

In UNITY2019.4 version plus MRTK 2.4 and 2.5.1, the same error will appear
I want to ask if there are any suggestions to improve this error. 
Thank you very much!

![messageImage_1626843210896](https://user-images.githubusercontent.com/80736252/126432962-9702969e-a7d9-49fd-8eb5-499b54a0c90e.jpg)

**Comment by HUIMANDY** [comment]
![messageImage_1626843143185](https://user-images.githubusercontent.com/80736252/126432885-8aee8b99-b213-4495-af83-8ebe7faca51b.jpg)

**Comment by LocalJoost** [comment]
Hello @HUIMANDY,

If you read [the accompanying blog post](https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/), especially the last part, you will see it will _only_ work in a HoloLens app, compiled for Master. It does _not_ work using _any_ other configuration, including Holographic Remoting. Because then you are actually running it from the Unity editor.

**Comment by HUIMANDY** [comment]
Thank you for your response!
I really appreciate! Thank you

**Comment by LocalJoost** [comment]
You are welcome!
